"""initial_schema

Revision ID: e54babdf6aab
Revises: 
Create Date: 2026-02-13 20:09:09.195722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e54babdf6aab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_news_published', 'news_articles', ['published_at'], unique=False)
    op.create_index('idx_news_source', 'news_articles', ['source'], unique=False)
    op.create_table('real_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('tla', sa.String(length=5), nullable=True),
    sa.Column('crest_url', sa.String(length=500), nullable=True),
    sa.Column('crest_local', sa.String(length=255), nullable=True),
    sa.Column('jersey_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('stadium', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('thesportsdb_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fantasy_leagues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('invite_code', sa.String(length=20), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scoring_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('goal_threshold', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('goal_step', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('kick_off', sa.DateTime(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['real_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['real_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_matches_kick_off', 'matches', ['kick_off'], unique=False)
    op.create_index('idx_matches_matchday', 'matches', ['matchday'], unique=False)
    op.create_index('idx_matches_status', 'matches', ['status'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('real_team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=3), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('photo_local', sa.String(length=255), nullable=True),
    sa.Column('cutout_url', sa.String(length=500), nullable=True),
    sa.Column('cutout_local', sa.String(length=255), nullable=True),
    sa.Column('thesportsdb_id', sa.String(length=20), nullable=True),
    sa.Column('bzzoiro_id', sa.String(length=20), nullable=True),
    sa.Column('initial_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['real_team_id'], ['real_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_players_position', 'players', ['position'], unique=False)
    op.create_index('idx_players_team', 'players', ['real_team_id'], unique=False)
    op.create_table('fantasy_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('budget_remaining', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['fantasy_leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_fantasy_teams_league_user')
    )
    op.create_table('match_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('assist_player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('extra_minute', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assist_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['real_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_events_match', 'match_events', ['match_id'], unique=False)
    op.create_index('idx_match_events_player', 'match_events', ['player_id'], unique=False)
    op.create_index('idx_match_events_type', 'match_events', ['event_type'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('expected_goals', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('expected_assists', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('total_passes', sa.Integer(), nullable=False),
    sa.Column('accurate_passes', sa.Integer(), nullable=False),
    sa.Column('key_passes', sa.Integer(), nullable=False),
    sa.Column('total_crosses', sa.Integer(), nullable=False),
    sa.Column('accurate_crosses', sa.Integer(), nullable=False),
    sa.Column('total_long_balls', sa.Integer(), nullable=False),
    sa.Column('accurate_long_balls', sa.Integer(), nullable=False),
    sa.Column('total_tackles', sa.Integer(), nullable=False),
    sa.Column('tackles_won', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('clearances', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('clean_sheet', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', name='idx_player_stats_unique')
    )
    op.create_index('idx_player_stats_match', 'player_stats', ['match_id'], unique=False)
    op.create_table('auction_bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['fantasy_leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bids_league', 'auction_bids', ['league_id'], unique=False)
    op.create_index('idx_bids_player', 'auction_bids', ['player_id'], unique=False)
    op.create_table('fantasy_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.UUID(), nullable=False),
    sa.Column('away_team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['fantasy_leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'matchday', 'home_team_id', name='uq_fantasy_calendar_league_matchday_home')
    )
    op.create_table('fantasy_lineups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position_slot', sa.String(length=10), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('bench_order', sa.Integer(), nullable=True),
    sa.Column('formation', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_team_id', 'matchday', 'player_id', name='uq_fantasy_lineups_team_matchday_player')
    )
    op.create_index('idx_lineup_team_matchday', 'fantasy_lineups', ['fantasy_team_id', 'matchday'], unique=False)
    op.create_table('fantasy_player_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('base_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('advanced_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('was_subbed_in', sa.Boolean(), nullable=False),
    sa.Column('events_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_team_id', 'player_id', 'matchday', name='uq_fantasy_player_scores_team_player_matchday')
    )
    op.create_table('fantasy_rosters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_team_id', 'player_id', name='uq_fantasy_rosters_team_player')
    )
    op.create_index('idx_roster_team', 'fantasy_rosters', ['fantasy_team_id'], unique=False)
    op.create_table('fantasy_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fantasy_goals', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.UUID(), nullable=True),
    sa.Column('opponent_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('opponent_goals', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=1), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_id'], ['fantasy_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_team_id', 'matchday', name='uq_fantasy_scores_team_matchday')
    )
    op.create_index('idx_scores_matchday', 'fantasy_scores', ['matchday'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('from_team_id', sa.UUID(), nullable=True),
    sa.Column('to_team_id', sa.UUID(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('transfer_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['fantasy_leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['fantasy_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_index('idx_scores_matchday', table_name='fantasy_scores')
    op.drop_table('fantasy_scores')
    op.drop_index('idx_roster_team', table_name='fantasy_rosters')
    op.drop_table('fantasy_rosters')
    op.drop_table('fantasy_player_scores')
    op.drop_index('idx_lineup_team_matchday', table_name='fantasy_lineups')
    op.drop_table('fantasy_lineups')
    op.drop_table('fantasy_calendar')
    op.drop_index('idx_bids_player', table_name='auction_bids')
    op.drop_index('idx_bids_league', table_name='auction_bids')
    op.drop_table('auction_bids')
    op.drop_index('idx_player_stats_match', table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index('idx_match_events_type', table_name='match_events')
    op.drop_index('idx_match_events_player', table_name='match_events')
    op.drop_index('idx_match_events_match', table_name='match_events')
    op.drop_table('match_events')
    op.drop_table('fantasy_teams')
    op.drop_index('idx_players_team', table_name='players')
    op.drop_index('idx_players_position', table_name='players')
    op.drop_table('players')
    op.drop_index('idx_matches_status', table_name='matches')
    op.drop_index('idx_matches_matchday', table_name='matches')
    op.drop_index('idx_matches_kick_off', table_name='matches')
    op.drop_table('matches')
    op.drop_table('fantasy_leagues')
    op.drop_table('users')
    op.drop_table('real_teams')
    op.drop_index('idx_news_source', table_name='news_articles')
    op.drop_index('idx_news_published', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
